// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace Moviet.RecommendationModel
{
    public class ModelOutput
    {
        public float Score { get; set; }
    }
}
