// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Moviet.RecommendationModel
{
    public class ModelInput
    {
        [ColumnName("RatingId"), LoadColumn(0)]
        public float RatingId { get; set; }


        [ColumnName("RaterId"), LoadColumn(1)]
        public float RaterId { get; set; }


        [ColumnName("Value"), LoadColumn(2)]
        public float Value { get; set; }


        [ColumnName("DateRated"), LoadColumn(3)]
        public string DateRated { get; set; }


        [ColumnName("MovieId"), LoadColumn(4)]
        public float MovieId { get; set; }


    }
}
