// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Data;
using MovietML.Model;
using Microsoft.ML.Trainers;
using Moviet.Data;
using System.Threading.Tasks;

namespace MovietML.ConsoleApp
{
    public static class ModelBuilder
    {
        private static string TRAIN_DATA_FILEPATH = @"C:\Users\geomimo\AppData\Local\Temp\TrainData.tsv";
        private static string MODEL_FILEPATH = @"C:\Users\geomimo\AppData\Local\Temp\MLVSTools\MovietML\MovietML.Model\MLModel.zip";
        // Create MLContext to be shared across the model creation workflow objects 
        // Set a random seed for repeatable/deterministic results across multiple trainings.
        private static MLContext mlContext = new MLContext(seed: 1);

        public static EvaluationResults CreateModel(List<Rating> data)
        {
            // Export Data to .tsv
            ExportData(data).Wait();

            // Load Data
            IDataView trainingDataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: TRAIN_DATA_FILEPATH,
                                            hasHeader: true,
                                            separatorChar: '\t',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Build training pipeline
            IEstimator<ITransformer> trainingPipeline = BuildTrainingPipeline(mlContext);

            // Train Model
            ITransformer mlModel = TrainModel(mlContext, trainingDataView, trainingPipeline);

            // Evaluate quality of Model
            var results = Evaluate(mlContext, trainingDataView, trainingPipeline);

            // Save model
            SaveModel(mlContext, mlModel, MODEL_FILEPATH, trainingDataView.Schema);

            return results;
        }

        public static async Task ExportData(List<Rating> data)
        {
            string[] lines = new string[data.Count() + 1];
            lines[0] = "RatingId\tRaterId\tValue\tDateRated\tMovieId";
            for(int i = 1; i < data.Count() + 1; i++)
            {
                lines[i] = data[i].RatingId.ToString() + "\t" +
                           data[i].RaterId.ToString() + "\t" +
                           data[i].Value.ToString() + "\t" +
                           data[i].DateRated.ToString() + "\t" +
                           data[i].MovieId.ToString();
            }
            await File.WriteAllLinesAsync(TRAIN_DATA_FILEPATH, lines);
        }

        public static IEstimator<ITransformer> BuildTrainingPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations 
            var dataProcessPipeline = mlContext.Transforms.Conversion.MapValueToKey("RaterId", "RaterId")
                                      .Append(mlContext.Transforms.Conversion.MapValueToKey("MovieId", "MovieId"));
            // Set the training algorithm 
            var trainer = mlContext.Recommendation().Trainers.MatrixFactorization(new MatrixFactorizationTrainer.Options() { NumberOfIterations = 10, LearningRate = 0.1f, ApproximationRank = 64, Lambda = 0.05f, LossFunction = MatrixFactorizationTrainer.LossFunctionType.SquareLossRegression, Alpha = 1E-06f, C = 0.0001f, LabelColumnName = "Value", MatrixColumnIndexColumnName = "RaterId", MatrixRowIndexColumnName = "MovieId" });

            var trainingPipeline = dataProcessPipeline.Append(trainer);

            return trainingPipeline;
        }

        public static ITransformer TrainModel(MLContext mlContext, IDataView trainingDataView, IEstimator<ITransformer> trainingPipeline)
        {
            Console.WriteLine("=============== Training  model ===============");

            ITransformer model = trainingPipeline.Fit(trainingDataView);

            Console.WriteLine("=============== End of training process ===============");
            return model;
        }

        private static EvaluationResults Evaluate(MLContext mlContext, IDataView trainingDataView, IEstimator<ITransformer> trainingPipeline)
        {
            // Cross-Validate with single dataset (since we don't have two datasets, one for training and for evaluate)
            // in order to evaluate and get the model's accuracy metrics
            Console.WriteLine("=============== Cross-validating to get model's accuracy metrics ===============");
            var crossValidationResults = mlContext.Regression.CrossValidate(trainingDataView, trainingPipeline, 10);

            var results = PrintRegressionFoldsAverageMetrics(crossValidationResults);

            return results;
        }

        private static void SaveModel(MLContext mlContext, ITransformer mlModel, string modelRelativePath, DataViewSchema modelInputSchema)
        {
            // Save/persist the trained model to a .ZIP file
            Console.WriteLine($"=============== Saving the model  ===============");
            mlContext.Model.Save(mlModel, modelInputSchema, GetAbsolutePath(modelRelativePath));
            Console.WriteLine("The model is saved to {0}", GetAbsolutePath(modelRelativePath));
        }

        public static string GetAbsolutePath(string relativePath)
        {
            FileInfo _dataRoot = new FileInfo(typeof(Program).Assembly.Location);
            string assemblyFolderPath = _dataRoot.Directory.FullName;

            string fullPath = Path.Combine(assemblyFolderPath, relativePath);

            return fullPath;
        }

        public static void PrintRegressionMetrics(RegressionMetrics metrics)
        {
            Console.WriteLine($"*************************************************");
            Console.WriteLine($"*       Metrics for Recommendation model      ");
            Console.WriteLine($"*------------------------------------------------");
            Console.WriteLine($"*       LossFn:        {metrics.LossFunction:0.##}");
            Console.WriteLine($"*       R2 Score:      {metrics.RSquared:0.##}");
            Console.WriteLine($"*       Absolute loss: {metrics.MeanAbsoluteError:#.##}");
            Console.WriteLine($"*       Squared loss:  {metrics.MeanSquaredError:#.##}");
            Console.WriteLine($"*       RMS loss:      {metrics.RootMeanSquaredError:#.##}");
            Console.WriteLine($"*************************************************");
        }

        public static EvaluationResults PrintRegressionFoldsAverageMetrics(IEnumerable<TrainCatalogBase.CrossValidationResult<RegressionMetrics>> crossValidationResults)
        {
            var results = new EvaluationResults()
            {
                L1 = crossValidationResults.Select(r => r.Metrics.MeanAbsoluteError).Average(),
                L2 = crossValidationResults.Select(r => r.Metrics.MeanSquaredError).Average(),
                RMS = crossValidationResults.Select(r => r.Metrics.RootMeanSquaredError).Average(),
                LossFunction = crossValidationResults.Select(r => r.Metrics.LossFunction).Average(),
                R2 = crossValidationResults.Select(r => r.Metrics.RSquared).Average()
            };
            

            Console.WriteLine($"*************************************************************************************************************");
            Console.WriteLine($"*       Metrics for Recommendation model      ");
            Console.WriteLine($"*------------------------------------------------------------------------------------------------------------");
            Console.WriteLine($"*       Average L1 Loss:       {results.L1:0.###} ");
            Console.WriteLine($"*       Average L2 Loss:       {results.L2:0.###}  ");
            Console.WriteLine($"*       Average RMS:           {results.RMS:0.###}  ");
            Console.WriteLine($"*       Average Loss Function: {results.LossFunction:0.###}  ");
            Console.WriteLine($"*       Average R-squared:     {results.R2:0.###}  ");
            Console.WriteLine($"*************************************************************************************************************");

            return results;
        }
    }
}
